definitions:
  models.Category:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      petshop_id:
        type: integer
      updated_at:
        type: string
    type: object
  models.Client:
    properties:
      address:
        type: string
      created_at:
        description: Corrigido create_at para created_at
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      observations:
        type: string
      pets:
        items:
          $ref: '#/definitions/models.Pet'
        type: array
      petshop_id:
        type: integer
      phone:
        type: string
      updated_at:
        type: string
    type: object
  models.Employee:
    properties:
      active:
        type: string
      cellphone:
        type: string
      cpf:
        type: string
      created_at:
        description: |-
          UserID    int       `gorm:"column:user_id;foreignKey:UserID" json:"user_id"`
          User      User      `gorm:"foreignKey:UserID" json:"usuario"`
        type: string
      id:
        type: integer
      name:
        type: string
      petshop_id:
        type: integer
      updated_at:
        type: string
    type: object
  models.Modulo:
    properties:
      created_at:
        type: string
      descricao:
        type: string
      icone:
        description: Ícone para o menu
        type: string
      id:
        type: integer
      nome:
        type: string
      ordem:
        description: Ordem no menu
        type: integer
      rota:
        description: Rota principal do módulo
        type: string
      updated_at:
        type: string
    type: object
  models.Pet:
    properties:
      age:
        type: integer
      client_id:
        type: integer
      color:
        type: string
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      observation:
        type: string
      race:
        type: string
      sex:
        type: string
      size:
        type: string
      specie:
        type: string
      updated_at:
        type: string
      weight:
        type: number
    type: object
  models.Service:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      description:
        type: string
      duration:
        type: string
      id:
        type: integer
      name:
        type: string
      petshop_id:
        type: integer
      price:
        type: number
      updated_at:
        type: string
    type: object
  models.Tenant:
    properties:
      config:
        $ref: '#/definitions/models.WhitelabelConfig'
      created_at:
        type: string
      domain:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.TipoAcesso:
    properties:
      created_at:
        type: string
      descricao:
        type: string
      id:
        type: integer
      modulos:
        items:
          $ref: '#/definitions/models.Modulo'
        type: array
      nome:
        type: string
      updated_at:
        type: string
    type: object
  models.Users:
    properties:
      ativo:
        type: boolean
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      tipo_acesso:
        $ref: '#/definitions/models.TipoAcesso'
      tipo_acesso_id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  models.WhitelabelConfig:
    properties:
      api:
        properties:
          allowed_origins:
            items:
              type: string
            type: array
          rate_limit:
            type: integer
        type: object
      branding:
        properties:
          company_name:
            type: string
          logo_url:
            type: string
          primary_color:
            type: string
          secondary_color:
            type: string
        type: object
      features:
        properties:
          enable_feature_x:
            type: boolean
          enable_feature_y:
            type: boolean
          max_users:
            type: integer
        type: object
    type: object
info:
  contact: {}
paths:
  /client:
    get:
      consumes:
      - application/json
      description: deleta um cliente
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: boolean
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Deleta um cliente
      tags:
      - client
  /client/:id:
    get:
      consumes:
      - application/json
      description: Retorna um cliente
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tenant'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista um cliente
      tags:
      - client
  /clients:
    get:
      consumes:
      - application/json
      description: Retorna todos os clientes cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tenant'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os clientes
      tags:
      - client
  /pets:
    get:
      consumes:
      - application/json
      description: Retorna todos os pets cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: boolean
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os pets
      tags:
      - pets
  /pets/id:
    get:
      consumes:
      - application/json
      description: Retorna todos os pets cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Users'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os pets
      tags:
      - pets
swagger: "2.0"
