definitions:
  models.Clients:
    properties:
      created_at:
        type: string
      email:
        type: string
      endereco:
        type: string
      id:
        type: integer
      name:
        type: string
      petshop_id:
        type: integer
      telefone:
        type: string
      updated_at:
        type: string
    type: object
  models.Pet:
    properties:
      age:
        type: integer
      client_id:
        type: integer
      cor:
        type: string
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      port:
        type: string
      race:
        type: string
      specie:
        type: string
      updated_at:
        type: string
      weight:
        type: number
    type: object
  models.Role:
    enum:
    - admin
    - manager
    - customer
    type: string
    x-enum-varnames:
    - RoleAdmin
    - RoleManager
    - RoleCustomer
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      role:
        $ref: '#/definitions/models.Role'
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /client:
    get:
      consumes:
      - application/json
      description: deleta um cliente
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: boolean
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Deleta um cliente
      tags:
      - client
  /client/:id:
    get:
      consumes:
      - application/json
      description: Retorna um cliente
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Clients'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista um cliente
      tags:
      - client
  /clients:
    get:
      consumes:
      - application/json
      description: Retorna todos os clientes cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Clients'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os clientes
      tags:
      - client
  /pets:
    get:
      consumes:
      - application/json
      description: Retorna todos os pets cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: boolean
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os pets
      tags:
      - pets
  /pets/id:
    get:
      consumes:
      - application/json
      description: Retorna todos os pets cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os pets
      tags:
      - pets
swagger: "2.0"
