basePath: /api/v1
definitions:
  main.Pet:
    properties:
      id:
        description: ID do pet
        example: 1
        type: integer
      name:
        description: Nome do pet
        example: Rex
        type: string
      type:
        description: Tipo do animal
        example: Cachorro
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gerenciamento de petshop
  title: API do Petshop
  version: "1.0"
paths:
  /pets:
    get:
      consumes:
      - application/json
      description: Retorna todos os pets cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Pet'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os pets
      tags:
      - pets
swagger: "2.0"
